# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/smartisan/oxford/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/smartisan/oxford

PRODUCT_COPY_FILES += \
    vendor/smartisan/oxford/proprietary/vendor/lib64/hw/fingerprint.nvtfp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.nvtfp.so \
    vendor/smartisan/oxford/proprietary/vendor/lib64/libfpr_ca.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfpr_ca.so \
    vendor/smartisan/oxford/proprietary/vendor/lib64/libfpr_library.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfpr_library.so \
    vendor/smartisan/oxford/proprietary/vendor/lib64/libfpr_manager.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfpr_manager.so
